CREATE USER configadmin WITH PASSWORD '@WSX3edc';
CREATE DATABASE config;
GRANT ALL PRIVILEGES ON DATABASE config TO configadmin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO configadmin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO configadmin;
ALTER DATABASE config OWNER TO configadmin;